name: Android
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
  ANDROID_HOME: ${{github.workspace}}/android-sdk
  ANDROID_NDK_HOME: ${{github.workspace}}/android-ndk-r27c
  CC_aarch64_linux_android: aarch64-linux-android27-clang
  CXX_aarch64_linux_android: aarch64-linux-android27-clang++
  AR_aarch64_linux_android: llvm-ar
  CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER: aarch64-linux-android27-clang
  CARGO_TERM_VERBOSE: true

jobs:
  v8a:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - run: |
          sudo apt-get update
          sudo apt-get install -y\
            git \
            gcc-multilib \
            g++-multilib \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            python3 \
            python3-pip \
            libfontconfig1-dev \
            libfreetype6-dev \
            libgl1-mesa-dev \
            clang \
            lld \
            fontconfig \
            openssl \
            libssl-dev \
            libfontconfig1-dev 
      
      - name: Install Android Tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $ANDROID_HOME
          yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools" "build-tools;33.0.2" "platforms;android-35"
          wget https://googledownloads.cn/android/repository/android-ndk-r27c-linux.zip
          unzip android-ndk-r27c-linux.zip -d ${{github.workspace}}
      
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup Rust
        uses: moonrepo/setup-rust@v1
        with:
          targets: 'aarch64-linux-android'
      
      - name: Test Toolchains
        run: |
          export PATH=$PATH:$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/
          aarch64-linux-android27-clang --version
          python3 --version
          ninja --version
          node --version
          cargo --version
          rustc --version
      
      - name: Build
        run: |
          npm install
          npm run build -- --release
      
      - name: Upload Skia Canvas Artifact
        uses: actions/upload-artifact@v4
        with:
          path: lib/v8/index.node
        
      - name: Clone Nodejs Android
        run: |
          git clone https://github.com/nodejs-mobile/nodejs-mobile
          cd nodejs-mobile
          git checkout mobile-master
      
      - name: Build Nodejs Android
        run: |
          nodejs-mobile/tools/android_build.sh $ANDROID_NDK_HOME arm64
          
      - name: Upload Nodejs Android Artifact
        uses: actions/upload-artifact@v4
        with:
          path: nodejs-mobile/out_android/arm64/libnode.so